//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTLogistics.Api.Services.Finkok
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facturacion.finkok.com/stamp", ConfigurationName="HTLogistics.Api.Services.Finkok.Application")]
    public interface Application
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="sign_stamp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.sign_stampResponse1> sign_stampAsync(HTLogistics.Api.Services.Finkok.sign_stamp1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="stamped", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.stampedResponse1> stampedAsync(HTLogistics.Api.Services.Finkok.stamped1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="stamp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.stampResponse1> stampAsync(HTLogistics.Api.Services.Finkok.stamp1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="stamp_async", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.stamp_asyncResponse1> stamp_asyncAsync(HTLogistics.Api.Services.Finkok.stamp_async1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="query_pending", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.query_pendingResponse1> query_pendingAsync(HTLogistics.Api.Services.Finkok.query_pending1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="get_pdf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.get_pdfResponse1> get_pdfAsync(HTLogistics.Api.Services.Finkok.get_pdf1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="quick_stamp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.quick_stampResponse1> quick_stampAsync(HTLogistics.Api.Services.Finkok.quick_stamp1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="get_result_async", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.get_result_asyncResponse1> get_result_asyncAsync(HTLogistics.Api.Services.Finkok.get_result_async1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class sign_stamp
    {
        
        private byte[] xmlField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://facturacion.finkok.com/servicios/async")]
    public partial class AcuseRecepcionAsync
    {
        
        private string uUIDField;
        
        private string rfcProvCertifField;
        
        private string noCertificadoSATField;
        
        private string codEstatusField;
        
        private string faultstringField;
        
        private string faultcodeField;
        
        private byte[] fileField;
        
        private string satSealField;
        
        private Incidencia[] incidenciasField;
        
        private System.Nullable<System.DateTime> fechaTimbradoField;
        
        private bool fechaTimbradoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string RfcProvCertif
        {
            get
            {
                return this.rfcProvCertifField;
            }
            set
            {
                this.rfcProvCertifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string NoCertificadoSAT
        {
            get
            {
                return this.noCertificadoSATField;
            }
            set
            {
                this.noCertificadoSATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string CodEstatus
        {
            get
            {
                return this.codEstatusField;
            }
            set
            {
                this.codEstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string faultstring
        {
            get
            {
                return this.faultstringField;
            }
            set
            {
                this.faultstringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string faultcode
        {
            get
            {
                return this.faultcodeField;
            }
            set
            {
                this.faultcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=6)]
        public byte[] file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string SatSeal
        {
            get
            {
                return this.satSealField;
            }
            set
            {
                this.satSealField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="apps.services.soap.core.views")]
        public Incidencia[] Incidencias
        {
            get
            {
                return this.incidenciasField;
            }
            set
            {
                this.incidenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> FechaTimbrado
        {
            get
            {
                return this.fechaTimbradoField;
            }
            set
            {
                this.fechaTimbradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaTimbradoSpecified
        {
            get
            {
                return this.fechaTimbradoFieldSpecified;
            }
            set
            {
                this.fechaTimbradoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class Incidencia
    {
        
        private string idIncidenciaField;
        
        private string rfcEmisorField;
        
        private string uuidField;
        
        private string codigoErrorField;
        
        private string workProcessIdField;
        
        private string mensajeIncidenciaField;
        
        private string extraInfoField;
        
        private string noCertificadoPacField;
        
        private string fechaRegistroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string IdIncidencia
        {
            get
            {
                return this.idIncidenciaField;
            }
            set
            {
                this.idIncidenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string RfcEmisor
        {
            get
            {
                return this.rfcEmisorField;
            }
            set
            {
                this.rfcEmisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string CodigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string WorkProcessId
        {
            get
            {
                return this.workProcessIdField;
            }
            set
            {
                this.workProcessIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string MensajeIncidencia
        {
            get
            {
                return this.mensajeIncidenciaField;
            }
            set
            {
                this.mensajeIncidenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ExtraInfo
        {
            get
            {
                return this.extraInfoField;
            }
            set
            {
                this.extraInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string NoCertificadoPac
        {
            get
            {
                return this.noCertificadoPacField;
            }
            set
            {
                this.noCertificadoPacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string FechaRegistro
        {
            get
            {
                return this.fechaRegistroField;
            }
            set
            {
                this.fechaRegistroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class get_result_asyncResponse
    {
        
        private AcuseRecepcionAsync get_result_asyncResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public AcuseRecepcionAsync get_result_asyncResult
        {
            get
            {
                return this.get_result_asyncResultField;
            }
            set
            {
                this.get_result_asyncResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class get_result_async
    {
        
        private string idField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class quick_stampResponse
    {
        
        private AcuseRecepcionCFDI quick_stampResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public AcuseRecepcionCFDI quick_stampResult
        {
            get
            {
                return this.quick_stampResultField;
            }
            set
            {
                this.quick_stampResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class AcuseRecepcionCFDI
    {
        
        private string xmlField;
        
        private string uUIDField;
        
        private string faultstringField;
        
        private string fechaField;
        
        private string codEstatusField;
        
        private string faultcodeField;
        
        private string satSealField;
        
        private Incidencia[] incidenciasField;
        
        private string noCertificadoSATField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string faultstring
        {
            get
            {
                return this.faultstringField;
            }
            set
            {
                this.faultstringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string CodEstatus
        {
            get
            {
                return this.codEstatusField;
            }
            set
            {
                this.codEstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string faultcode
        {
            get
            {
                return this.faultcodeField;
            }
            set
            {
                this.faultcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string SatSeal
        {
            get
            {
                return this.satSealField;
            }
            set
            {
                this.satSealField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=7)]
        public Incidencia[] Incidencias
        {
            get
            {
                return this.incidenciasField;
            }
            set
            {
                this.incidenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string NoCertificadoSAT
        {
            get
            {
                return this.noCertificadoSATField;
            }
            set
            {
                this.noCertificadoSATField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class quick_stamp
    {
        
        private byte[] xmlField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class PDFResult
    {
        
        private byte[] pdfField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] pdf
        {
            get
            {
                return this.pdfField;
            }
            set
            {
                this.pdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class get_pdfResponse
    {
        
        private PDFResult get_pdfResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public PDFResult get_pdfResult
        {
            get
            {
                return this.get_pdfResultField;
            }
            set
            {
                this.get_pdfResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class get_pdf
    {
        
        private string usernameField;
        
        private string passwordField;
        
        private string uuidField;
        
        private string notesField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class QueryPendingResult
    {
        
        private string statusField;
        
        private string xmlField;
        
        private string uuidField;
        
        private string uuid_statusField;
        
        private string next_attemptField;
        
        private string attemptsField;
        
        private string errorField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string uuid_status
        {
            get
            {
                return this.uuid_statusField;
            }
            set
            {
                this.uuid_statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string next_attempt
        {
            get
            {
                return this.next_attemptField;
            }
            set
            {
                this.next_attemptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string attempts
        {
            get
            {
                return this.attemptsField;
            }
            set
            {
                this.attemptsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class query_pendingResponse
    {
        
        private QueryPendingResult query_pendingResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public QueryPendingResult query_pendingResult
        {
            get
            {
                return this.query_pendingResultField;
            }
            set
            {
                this.query_pendingResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class query_pending
    {
        
        private string usernameField;
        
        private string passwordField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class ResultAsync
    {
        
        private string statusField;
        
        private Incidencia[] incidenciasField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public Incidencia[] Incidencias
        {
            get
            {
                return this.incidenciasField;
            }
            set
            {
                this.incidenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class stamp_asyncResponse
    {
        
        private ResultAsync stamp_asyncResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public ResultAsync stamp_asyncResult
        {
            get
            {
                return this.stamp_asyncResultField;
            }
            set
            {
                this.stamp_asyncResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class stamp_async
    {
        
        private byte[] fileField;
        
        private string usernameField;
        
        private string passwordField;
        
        private stamp_async_ctypeType ctypeField;
        
        private bool ctypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public stamp_async_ctypeType ctype
        {
            get
            {
                return this.ctypeField;
            }
            set
            {
                this.ctypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ctypeSpecified
        {
            get
            {
                return this.ctypeFieldSpecified;
            }
            set
            {
                this.ctypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public enum stamp_async_ctypeType
    {
        
        /// <remarks/>
        zip,
        
        /// <remarks/>
        gzip,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class stampResponse
    {
        
        private AcuseRecepcionCFDI stampResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public AcuseRecepcionCFDI stampResult
        {
            get
            {
                return this.stampResultField;
            }
            set
            {
                this.stampResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class stamp
    {
        
        private byte[] xmlField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class stampedResponse
    {
        
        private AcuseRecepcionCFDI stampedResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public AcuseRecepcionCFDI stampedResult
        {
            get
            {
                return this.stampedResultField;
            }
            set
            {
                this.stampedResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class stamped
    {
        
        private byte[] xmlField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class sign_stampResponse
    {
        
        private AcuseRecepcionCFDI sign_stampResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public AcuseRecepcionCFDI sign_stampResult
        {
            get
            {
                return this.sign_stampResultField;
            }
            set
            {
                this.sign_stampResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sign_stamp1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.sign_stamp sign_stamp;
        
        public sign_stamp1()
        {
        }
        
        public sign_stamp1(HTLogistics.Api.Services.Finkok.sign_stamp sign_stamp)
        {
            this.sign_stamp = sign_stamp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sign_stampResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.sign_stampResponse sign_stampResponse;
        
        public sign_stampResponse1()
        {
        }
        
        public sign_stampResponse1(HTLogistics.Api.Services.Finkok.sign_stampResponse sign_stampResponse)
        {
            this.sign_stampResponse = sign_stampResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class stamped1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.stamped stamped;
        
        public stamped1()
        {
        }
        
        public stamped1(HTLogistics.Api.Services.Finkok.stamped stamped)
        {
            this.stamped = stamped;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class stampedResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.stampedResponse stampedResponse;
        
        public stampedResponse1()
        {
        }
        
        public stampedResponse1(HTLogistics.Api.Services.Finkok.stampedResponse stampedResponse)
        {
            this.stampedResponse = stampedResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class stamp1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.stamp stamp;
        
        public stamp1()
        {
        }
        
        public stamp1(HTLogistics.Api.Services.Finkok.stamp stamp)
        {
            this.stamp = stamp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class stampResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.stampResponse stampResponse;
        
        public stampResponse1()
        {
        }
        
        public stampResponse1(HTLogistics.Api.Services.Finkok.stampResponse stampResponse)
        {
            this.stampResponse = stampResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class stamp_async1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.stamp_async stamp_async;
        
        public stamp_async1()
        {
        }
        
        public stamp_async1(HTLogistics.Api.Services.Finkok.stamp_async stamp_async)
        {
            this.stamp_async = stamp_async;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class stamp_asyncResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.stamp_asyncResponse stamp_asyncResponse;
        
        public stamp_asyncResponse1()
        {
        }
        
        public stamp_asyncResponse1(HTLogistics.Api.Services.Finkok.stamp_asyncResponse stamp_asyncResponse)
        {
            this.stamp_asyncResponse = stamp_asyncResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class query_pending1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.query_pending query_pending;
        
        public query_pending1()
        {
        }
        
        public query_pending1(HTLogistics.Api.Services.Finkok.query_pending query_pending)
        {
            this.query_pending = query_pending;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class query_pendingResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.query_pendingResponse query_pendingResponse;
        
        public query_pendingResponse1()
        {
        }
        
        public query_pendingResponse1(HTLogistics.Api.Services.Finkok.query_pendingResponse query_pendingResponse)
        {
            this.query_pendingResponse = query_pendingResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_pdf1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.get_pdf get_pdf;
        
        public get_pdf1()
        {
        }
        
        public get_pdf1(HTLogistics.Api.Services.Finkok.get_pdf get_pdf)
        {
            this.get_pdf = get_pdf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_pdfResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.get_pdfResponse get_pdfResponse;
        
        public get_pdfResponse1()
        {
        }
        
        public get_pdfResponse1(HTLogistics.Api.Services.Finkok.get_pdfResponse get_pdfResponse)
        {
            this.get_pdfResponse = get_pdfResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class quick_stamp1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.quick_stamp quick_stamp;
        
        public quick_stamp1()
        {
        }
        
        public quick_stamp1(HTLogistics.Api.Services.Finkok.quick_stamp quick_stamp)
        {
            this.quick_stamp = quick_stamp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class quick_stampResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.quick_stampResponse quick_stampResponse;
        
        public quick_stampResponse1()
        {
        }
        
        public quick_stampResponse1(HTLogistics.Api.Services.Finkok.quick_stampResponse quick_stampResponse)
        {
            this.quick_stampResponse = quick_stampResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_result_async1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.get_result_async get_result_async;
        
        public get_result_async1()
        {
        }
        
        public get_result_async1(HTLogistics.Api.Services.Finkok.get_result_async get_result_async)
        {
            this.get_result_async = get_result_async;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_result_asyncResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facturacion.finkok.com/stamp", Order=0)]
        public HTLogistics.Api.Services.Finkok.get_result_asyncResponse get_result_asyncResponse;
        
        public get_result_asyncResponse1()
        {
        }
        
        public get_result_asyncResponse1(HTLogistics.Api.Services.Finkok.get_result_asyncResponse get_result_asyncResponse)
        {
            this.get_result_asyncResponse = get_result_asyncResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ApplicationChannel : HTLogistics.Api.Services.Finkok.Application, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ApplicationClient : System.ServiceModel.ClientBase<HTLogistics.Api.Services.Finkok.Application>, HTLogistics.Api.Services.Finkok.Application
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ApplicationClient() : 
                base(ApplicationClient.GetDefaultBinding(), ApplicationClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Application.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(EndpointConfiguration endpointConfiguration) : 
                base(ApplicationClient.GetBindingForEndpoint(endpointConfiguration), ApplicationClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ApplicationClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ApplicationClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.sign_stampResponse1> HTLogistics.Api.Services.Finkok.Application.sign_stampAsync(HTLogistics.Api.Services.Finkok.sign_stamp1 request)
        {
            return base.Channel.sign_stampAsync(request);
        }
        
        public System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.sign_stampResponse1> sign_stampAsync(HTLogistics.Api.Services.Finkok.sign_stamp sign_stamp)
        {
            HTLogistics.Api.Services.Finkok.sign_stamp1 inValue = new HTLogistics.Api.Services.Finkok.sign_stamp1();
            inValue.sign_stamp = sign_stamp;
            return ((HTLogistics.Api.Services.Finkok.Application)(this)).sign_stampAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.stampedResponse1> HTLogistics.Api.Services.Finkok.Application.stampedAsync(HTLogistics.Api.Services.Finkok.stamped1 request)
        {
            return base.Channel.stampedAsync(request);
        }
        
        public System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.stampedResponse1> stampedAsync(HTLogistics.Api.Services.Finkok.stamped stamped)
        {
            HTLogistics.Api.Services.Finkok.stamped1 inValue = new HTLogistics.Api.Services.Finkok.stamped1();
            inValue.stamped = stamped;
            return ((HTLogistics.Api.Services.Finkok.Application)(this)).stampedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.stampResponse1> HTLogistics.Api.Services.Finkok.Application.stampAsync(HTLogistics.Api.Services.Finkok.stamp1 request)
        {
            return base.Channel.stampAsync(request);
        }
        
        public System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.stampResponse1> stampAsync(HTLogistics.Api.Services.Finkok.stamp stamp)
        {
            HTLogistics.Api.Services.Finkok.stamp1 inValue = new HTLogistics.Api.Services.Finkok.stamp1();
            inValue.stamp = stamp;
            return ((HTLogistics.Api.Services.Finkok.Application)(this)).stampAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.stamp_asyncResponse1> HTLogistics.Api.Services.Finkok.Application.stamp_asyncAsync(HTLogistics.Api.Services.Finkok.stamp_async1 request)
        {
            return base.Channel.stamp_asyncAsync(request);
        }
        
        public System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.stamp_asyncResponse1> stamp_asyncAsync(HTLogistics.Api.Services.Finkok.stamp_async stamp_async)
        {
            HTLogistics.Api.Services.Finkok.stamp_async1 inValue = new HTLogistics.Api.Services.Finkok.stamp_async1();
            inValue.stamp_async = stamp_async;
            return ((HTLogistics.Api.Services.Finkok.Application)(this)).stamp_asyncAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.query_pendingResponse1> HTLogistics.Api.Services.Finkok.Application.query_pendingAsync(HTLogistics.Api.Services.Finkok.query_pending1 request)
        {
            return base.Channel.query_pendingAsync(request);
        }
        
        public System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.query_pendingResponse1> query_pendingAsync(HTLogistics.Api.Services.Finkok.query_pending query_pending)
        {
            HTLogistics.Api.Services.Finkok.query_pending1 inValue = new HTLogistics.Api.Services.Finkok.query_pending1();
            inValue.query_pending = query_pending;
            return ((HTLogistics.Api.Services.Finkok.Application)(this)).query_pendingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.get_pdfResponse1> HTLogistics.Api.Services.Finkok.Application.get_pdfAsync(HTLogistics.Api.Services.Finkok.get_pdf1 request)
        {
            return base.Channel.get_pdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.get_pdfResponse1> get_pdfAsync(HTLogistics.Api.Services.Finkok.get_pdf get_pdf)
        {
            HTLogistics.Api.Services.Finkok.get_pdf1 inValue = new HTLogistics.Api.Services.Finkok.get_pdf1();
            inValue.get_pdf = get_pdf;
            return ((HTLogistics.Api.Services.Finkok.Application)(this)).get_pdfAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.quick_stampResponse1> HTLogistics.Api.Services.Finkok.Application.quick_stampAsync(HTLogistics.Api.Services.Finkok.quick_stamp1 request)
        {
            return base.Channel.quick_stampAsync(request);
        }
        
        public System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.quick_stampResponse1> quick_stampAsync(HTLogistics.Api.Services.Finkok.quick_stamp quick_stamp)
        {
            HTLogistics.Api.Services.Finkok.quick_stamp1 inValue = new HTLogistics.Api.Services.Finkok.quick_stamp1();
            inValue.quick_stamp = quick_stamp;
            return ((HTLogistics.Api.Services.Finkok.Application)(this)).quick_stampAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.get_result_asyncResponse1> HTLogistics.Api.Services.Finkok.Application.get_result_asyncAsync(HTLogistics.Api.Services.Finkok.get_result_async1 request)
        {
            return base.Channel.get_result_asyncAsync(request);
        }
        
        public System.Threading.Tasks.Task<HTLogistics.Api.Services.Finkok.get_result_asyncResponse1> get_result_asyncAsync(HTLogistics.Api.Services.Finkok.get_result_async get_result_async)
        {
            HTLogistics.Api.Services.Finkok.get_result_async1 inValue = new HTLogistics.Api.Services.Finkok.get_result_async1();
            inValue.get_result_async = get_result_async;
            return ((HTLogistics.Api.Services.Finkok.Application)(this)).get_result_asyncAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Application))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Application))
            {
                return new System.ServiceModel.EndpointAddress("https://demo-facturacion.finkok.com/servicios/soap/stamp");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ApplicationClient.GetBindingForEndpoint(EndpointConfiguration.Application);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ApplicationClient.GetEndpointAddress(EndpointConfiguration.Application);
        }
        
        public enum EndpointConfiguration
        {
            
            Application,
        }
    }
}
